// Generated by CoffeeScript 1.3.3
(function() {

  this.templates.flickr = "<!--\n{\n  \"pictures\": {\n    {\n      \"uri\": ,\n      \"alt\": ,\n      \"title\": ,\n      \"description\": ,\n    },\n  },\n}\n-->\n\n<div class=\"span9\">\n  <h2>\n    flickr\n    <small>Pictures &amp; Adventures!</small>\n  </h2>\n</div>\n<div class=\"span2\">\n<h2><small><a href='http://www.flickr.com/user/toby.waite'>toby.waite</a></small></h2>\n</div>\n<div id='flickrCarousel' class='carousel'>\n  <div class='carousel-inner'>\n    {{#pictures}}\n    <div class='item'>\n      <img src='{{uri}}' alt='{{alt}}'>\n      <div class='carousel-caption'>\n        <h4>{{title}}</h4>\n        <p>{{description}}</p>\n      </div>\n    </div>\n    {{/pictures}}\n  </div>\n  <a class='carousel-control left' href='#flickrCarousel' data-slide='prev'>&lsaquo;</a>\n  <a class='carousel-control right' href='#flickrCarousel' data-slide='next'>&rsaquo;</a>\n</div>";

}).call(this);
