// Generated by CoffeeScript 1.3.3
(function() {

  this.templates.github = "<!--\n\n{\n  \"repo-url\": ,\n  \"repo-name\": ,\n  \"repo-desc\": ,\n  \"commit-message\": ,\n  \"commit-date\": ,\n  \"commit-time\": ,\n}\n\n-->\n\n\n<h2>\n  github\n  <small><a href='http://www.github.com/users/tobywaite'>tobywaite</a></small>\n</h2>\n<div class=\"row\">\n  <div class='span1'>\n    <img class='logo' src='img/octocat.png' alt='octocat!'>\n  </div>\n  <div class='span4'>\n    <h3>\n      Repo:\n      <small><a href='{{repo-url}}'>{{repo-name}}</a></small>\n    </h3>\n    <p>{{repo-desc}}</p>\n    <blockquote>\n      {{commit-message}}\n      <small>latest commit, {{commit-date}}@{{commit-time}}</small>\n    </blockquote>\n  </div>\n</div>";

}).call(this);
