// Generated by CoffeeScript 1.3.3
(function() {

  this.templates.lastfm = "<!--\n\n{\n  \"now-playing\": true,\n  \"song\": \"Song Name\",\n  \"artist\": \"Artist Name\",\n  \"album\": \"Album Name\",\n  \"art-uri\": \"http://www.art.com/album/haters.jpg\"\n}\n\n-->\n\n<h2>\n  last.fm\n  <small><a href='http://www.last.fm/users/thebrokenfish'>thebrokenfish</a></small>\n</h2>\n<div class=\"row\">\n  <div class='span1'>\n    <img class='logo' src='img/lastfm_logo.png' alt=\"everyday we scrobblin'\">\n  </div>\n  <div class='span3'>\n    <h3>\n      Listening to...\n      {{#now-playing}}\n        <small>Now playing!</small>\n      {{/now-playing}}\n    </h3>\n    <dl class='dl-horizontal'>\n      <dt>Song</dt>\n      <dd>{{song}}</dd>\n      <dt>Artist</dt>\n      <dd>{{artist}}</dd>\n      <dt>Album</dt>\n      <dd>{{album}}</dd>\n    </dl>\n  </div>\n  <div class='span1'>\n    <img class='logo' src='{{art-uri}}' alt=\"album-art\">\n  </div>\n</div>";

}).call(this);
