// Generated by CoffeeScript 1.3.3
(function() {

  this.templates.twitter = "<!--\n\n{\n  \"text\": ,\n  \"date\": ,\n  \"time\": ,\n  \"latest\": true,\n}\n\n-->\n\n<h2>\n  twitter\n  <small><a href='http://www.twitter.com/tobywaite'>@tobywaite</a></small>\n</h2>\n<div class=\"row\">\n  <div class='span1'>\n    <img class='logo' src='img/bird.png' alt='tweet tweet!'>\n  </div>\n  <div class='span4'>\n    <blockquote>\n      {{body}}\n      <small>blabbing to the universe, {{date}}@{{time}}</small>\n    </blockquote>\n    <ul class='pager'>\n      <li class='previous'>\n        <a href='#'>Older</a>\n      </li>\n      <li class='next {{#latest}}disabled{{/latest}}'>\n        <a href='#'>Newer</a>\n      </li>\n    </ul>\n  </div>\n</div>\n\n<!--\n\nRegister callbacks on the previous and next buttons to get more tweet data and re-render the template.\n\n-->";

}).call(this);
